config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#about'
    patch "withdrawal" => "users#withdrawal"
    get 'mypage' => 'users#mypage'
    patch 'user/now_location', to: 'users#now_location'
    get 'user/information/edit', to: 'users#edit', as: 'edit_user'
    get 'user/liked_posts', to: 'users#liked_posts', as: 'liked_posts'
    patch 'user/information', to: 'users#update', as: 'update_user'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :like, only: [:create, :destroy]
    end
    resources :notifications, only: :index
    get 'notifications/modal', to: 'notifications#modal'
    scope '/posts/:post_id' do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  namespace :admin do
    get '/' => 'users#index'
    patch "deactivate/:id" => "users#deactivate", as: "deactivate"
    patch "reactivate/:id" => "users#reactivate", as: "reactivate"
    resources :users, only: [:show, :edit, :update]
    resources :posts, only: [:destroy]
    resources :comments, only: [:show, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@kokotto.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def unread_notifications
    passive_notifications.where.not(visitor_id: id).where(has_read: false)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(:created_at).reverse_order.page(params[:page]).per(5)
    @comments = @user.comments.order(:created_at).reverse_order.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user = User.update(user_params)
      redirect_to request.referer, notice: "会員情報を編集しました"
    else
      render :edit
    end
  end

  def deactivate
    @user = User.find(params[:id])
    if @user.update(is_deleted: true)
      redirect_to request.referer, notice: "アカウントを無効にしました"
    else
      redirect_to request.referer, alert: "アカウントの無効化に失敗しました"
    end
  end

  def reactivate
    @user = User.find(params[:id])
    if @user.update(is_deleted: false)
      redirect_to request.referer, notice: "アカウントを有効にしました"
    else
      redirect_to request.referer, alert: "アカウントの有効化に失敗しました"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to admin_path, temprop: "item" do %>
      <span itemprop="name">User List</span>
    <% end %>
    <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to admin_user_path(@user), temprop: "item" do %>
      <span itemprop="name"><%= @user.name %></span>
    <% end %>
    <meta itemprop="position" content="2" />
  </li>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to edit_admin_user_path(@user), temprop: "item" do %>
      <span itemprop="name"><%= @user.name %> editing</span>
    <% end %>
    <meta itemprop="position" content="３" />
  </li>
</ol>

<%= form_with model: @user, url: admin_user_path(@user), method: :patch do |form| %>
  <div class="admin__user-headline">
    <div class="admin__title">
      <h1>
        <%= form.text_field :name %>
      </h1>
    </div>

    <div class="admin__user-item">
      <% if @user.is_deleted %>
        <div class="invalid-user">退会</div>
      <% else %>
        <div class="active-user">有効</div>
      <% end %>
    </div>
  </div>

  <div>アカウント開始日: <%= l @user.created_at, format: :short %></div>
  <div>
    メールアドレス:<%= @user.email %>
  </div>

  <div class="admin__editbtn-list">
    <%= form.submit "ユーザー情報を変更", class: "btn-s-notice" %>

    <% if @user.is_deleted %>
      <%= link_to "アカウントを有効に切り替え", admin_reactivate_path(@user.id), method: :patch, class: "btn-s-notice" %>
    <% else %>
      <%= link_to "アカウントを無効に切り替え", admin_deactivate_path(@user.id), method: :patch, class: "btn-s-danger" %>
    <% end %>
  </div>

<% end %>

app/views/admin/users/index.html.erb
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to admin_path, temprop: "item" do %>
      <span itemprop="name">User List</span>
    <% end %>
    <meta itemprop="position" content="1" />
  </li>
</ol>

<div class="admin__user-headline">
  <div class="title__circle--h2"></div>
  <div class="admin__title">
    <h1 class='title__text'>User List</h1>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>ユーザー名</th>
      <th class="table-optional-s">メールアドレス</th>
      <th></th>
      <th class="table-column-optional"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to admin_user_path(user), class: "admin__user-link" do %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="table-optional-s"><%= user.email %></td>
        <% if user.is_deleted %>
          <td class="invalid-user">退会</td>
        <% else %>
          <td class="active-user">有効</td>
        <% end %>
        <td class="table-optional-m">
          <%= link_to admin_user_path(user), class: "btn-s-light" do %>
            詳細
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/users/show.html.erb
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to admin_path, temprop: "item" do %>
      <span itemprop="name">User List</span>
    <% end %>
    <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to admin_user_path(@user), temprop: "item" do %>
      <span itemprop="name"><%= @user.name %></span>
    <% end %>
    <meta itemprop="position" content="2" />
  </li>
</ol>

<div class="admin__user-headline">
  <div class="admin__title">
    <h1 class='title__text'><%= @user.name %></h1>
  </div>
  <%= link_to edit_admin_user_path(@user) do %>
    <i class="fa-regular fa-pen-to-square admin__icon"></i>
  <% end %>

  <div class="admin__user-status">
    <% if @user.is_deleted %>
      <div class="invalid-user">退会</div>
    <% else %>
      <div class="active-user">有効</div>
    <% end %>
  </div>
</div>

<div>アカウント開始日: <%= l @user.created_at, format: :short %></div>
<div>メールアドレス: <%= @user.email %></div>

<div class="title">
  <div class="title__circle--h2"></div>
  <h2 class='title__text'>Tweet List</h2>
</div>
<% @posts.each do |post| %>
  <div class="card">
    <div class='card__inner'>
      <div class="card__flame">
        <div class="card__tag">
          <%= image_tag "tag/#{post.tag_name}", class: 'card__tagImg' %>
        </div>
        <div class="card__content">
          <p class="card__contentText">
            <%= post.text %>
          </p>
          <div class="card__contentImage">
            <% if post.image.attached? %>
              <%= image_tag post.image %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card__summary">
        <div class="card__summaryItem">
          <i class="fa-regular fa-clock"></i>
          <%= time_ago_in_words(post.created_at) %>
        </div>
        <div class="card__summaryItem">
          <i class="fa-solid fa-heart"></i>
          <%= post.likes.count %>
        </div>
        <div class="card__summaryItem">
          <i class="fa-regular fa-comment"></i>
          <%= post.comments.count %>
        </div>
        <div class="card__summaryItem">
          <%= link_to admin_post_path(post.id), method: :delete do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @posts %>

<div class="title">
  <div class="title__circle--h2"></div>
  <h2 class='form__title title__text'>Comment List</h2>
</div>
<% @comments.each do |comment| %>
  <div class="card">
    <div class="card__flame">
      <p class="card__contentText">
        <%= comment.text %>
      </p>
    </div>

    <div class="card__summary">
      <div class="card__summaryItem">
        <i class="fa-regular fa-clock"></i>
        <%= time_ago_in_words(comment.created_at) %>
      </div>
      <div class="card__summaryItem">
        <%= link_to admin_comment_path(comment.id), method: :delete do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @comments %>