config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#about'
    patch "withdrawal" => "users#withdrawal"
    get 'mypage' => 'users#mypage'
    patch 'user/now_location', to: 'users#now_location'
    get 'user/information/edit', to: 'users#edit', as: 'edit_user'
    get 'user/liked_posts', to: 'users#liked_posts', as: 'liked_posts'
    patch 'user/information', to: 'users#update', as: 'update_user'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :like, only: [:create, :destroy]
    end
    resources :notifications, only: :index
    get 'notifications/modal', to: 'notifications#modal'
    scope '/posts/:post_id' do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  namespace :admin do
    get '/' => 'users#index'
    patch "deactivate/:id" => "users#deactivate", as: "deactivate"
    patch "reactivate/:id" => "users#reactivate", as: "reactivate"
    resources :users, only: [:show, :edit, :update]
    resources :posts, only: [:destroy]
    resources :comments, only: [:show, :destroy]
  end

end

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |message_type, message| %>
    <div class="flash-message">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <svg preserveAspectRatio="none", xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
    <path fill="#CEA0C1" fill-opacity="1" d="M0,192L120,181.3C240,171,480,149,720,154.7C960,160,1200,192,1320,208L1440,224L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"></path>
  </svg>
  <p class="footer__text">
    ©︎ 2023 Rina-Kondo
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="logo">
    <%= link_to root_path do %>
       <span class="logo--Accent">Koko</span>tto
    <% end %>
  </div>
  <% if user_signed_in? %>
    <nav class="header__Nav">
      <ul class="header__NavList" >
        <li class="header__NavListItem">
          <div class="notification-button" id="notification-button" role="button" aria-label="Show notifications">
            <% if current_user.unread_notifications.exists? %>
              <div class="notification-button--alert">︎</div>
              <i class="fa-solid fa-bell"></i>
            <% else %>
              <i class="fa-solid fa-bell"></i>
            <% end %>
          </div>
        </li>
        <li class="header__NavListItem">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__NavListItemLink" %>
        </li>
      </ul>
    </nav>
  <% elsif admin_signed_in? %>
    <nav class="header__Nav">
      <ul class="header__NavList" %>
        <li class="header__NavListItem">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "header__NavListItemLink" %>
        </li>
      </ul>
    </nav>
  <% else %>
    <nav class="header__Nav--s" id="overlay">
      <ul class="header__NavList--s" %>
        <li class="header__NavListItem--s">
          <%= link_to root_path, class: "header__NavListItemLink--s" do %> What's Kokotto?<% end %>
        </li>
        <li class="header__NavListItem--s">
          <%= link_to "新規登録", new_user_registration_path, class: "header__NavListItemLink--s" %>
        </li>
        <li class="header__NavListItem--s">
          <%= link_to "ログイン", new_user_session_path, class: "header__NavListItemLink--s" %>
        </li>
        <li class="header__NavListItem--s">
          <%= link_to 'ゲストログイン', guest_sign_in_path, method: :post, class: "header__NavListItemLink--s" %>
        </li>
      </ul>
    </nav>
  <% end %>
  <% unless user_signed_in? || admin_signed_in? %>
    <div class="header__Hamburger" id="toggle">
      <span class="top"></span>
      <span class="middle"></span>
      <span class="bottom"></span>
    </div>
    <%= javascript_pack_tag 'hamburger.js' %>
  <% end %>
</header>

app/views/layouts/_loading.html.erb
<div class="loading">
  <h2 class="loading__text">
    <span class="char">N</span>
    <span class="char">o</span>
    <span class="char">w</span>
    <span class="char"> </span>
    <span class="char">L</span>
    <span class="char">o</span>
    <span class="char">a</span>
    <span class="char">d</span>
    <span class="char">i</span>
    <span class="char">n</span>
    <span class="char">g</span>
  </h2>
  <%= image_tag "loading/loading#{rand(1..13)}", class: "loading__image" %>
</div>

app/views/layouts/_menu.html.erb
<div class="menu">
  <div class="menu__list">
    <%= link_to posts_path(current_user), class: "menu__icon" do %>
      <i class="fa-solid fa-house-chimney"></i>
    <% end %>

    <%= link_to liked_posts_path(current_user), class: "menu__icon" do %>
      <i class="fa-solid fa-heart"></i>
    <% end %>

    <%= link_to mypage_path, class: "menu__icon" do %>
      <i class="fa-solid fa-user"></i>
    <% end %>

    <%= link_to new_post_path, class: 'menu__icon' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kokotto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/dec8a00012.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500&display=swap" rel="stylesheet">
    <link href=”https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;subset=japanese” rel=”stylesheet”>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="main">
      <%= render 'layouts/loading' %>
      <%= render "layouts/header" %>

      <div class="contents">
        <div class="sub-contents">
          <%= render "layouts/flash" %>
          <%= yield %>
        </div>
        <% if user_signed_in? %>
          <%= render "layouts/menu" %>
        <% end %>
      </div>

      <%= render "layouts/footer" %>
    </div>
  </body>
</html>